# Generated by Django 4.1.4 on 2023-01-08 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_category_women'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='women',
            name='cat',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Women',
        ),
    ]
